services:
  oracle-db:
    # Version "Slim" : Beaucoup plus légère et optimisée pour le dev
    image: gvenzl/oracle-free:slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment: # Définit le mot de passe pour SYS et SYSTEM
      ORACLE_PASSWORD: ${DB_PASSWORD}
      # Optionnel : crée directement un utilisateur pour Django
      APP_USER: ${DB_USER}
      APP_USER_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always

volumes:
  oracle_data: